# 公共配置
server:
  servlet:
    context-path: /community

spring:
  # 指定选择的配置文件
  profiles:
    active: app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.72.73:3306/community?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong
    username: remote
    password: Remote123
    # 数据库连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 60
      minimum-idle: 5
      idle-timeout: 30000
  # Mail
  mail:
    host: smtp.qq.com
    username: 1982125467@qq.com
    port: 465
    password: zcuemuorybxfbcca
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # Redis配置
  redis:
    database: 11
    host: 43.139.72.73
    password: Ue!p41Redis
  # kafka
  kafka:
    bootstrap-servers: 43.139.72.73:9092
    consumer:
      # 默认的组ID，先用着
      group-id: test-consumer-group
      # 是否自动提交偏移量
      enable-auto-commit: true
      # 自动提交频率
      auto-commit-interval: 3000
  # ElasticSearch
  elasticsearch:
    uris: 162.14.116.127:9200
  data:
    elasticsearch:
      cluster-name: myCluster2
      # 9300是TCP端口
      cluster-nodes: 162.14.116.127:9300
  # 普通线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    # 定时任务线程池
    scheduling:
      pool:
        size: 5
  # quartz
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
  # 解决Swagger3.0与SpringBoot2.6.x的路径兼容问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 增强Swagger的接口文档
knife4j:
  enable: true

# 注解开发不需要配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.community.entity
  configuration:
    use-generated-keys: true
    # 启用自动增长组件
    map-underscore-to-camel-case: true
    # 自动匹配驼峰和_命名方式
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true

caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

management:
  endpoints:
    web:
      exposure:
        include:
        exclude:

qiniu:
  key:
    access: q9NbbPV-TtgahQDOhCAjLHxNd-i6ocA3OP1CyNaV
    secret: jf1LSt5YD6N_ZmIyYO9-JUvE0hQ9tIkYlgtE1kvn
  bucket:
    header:
      name: community-user-header2url
      url: yaos.cc

wechat:
  appId: wx0523e122aa5962bc
  appSecret: bfd8069a759378e001585d91fb6d18ac

logging:
  level:
    org.mybatis: DEBUG